from quixo import Quixo

game = Quixo()


move = (13, 1)
game.opponent_play(move)
move = (13, 1)
game.opponent_play(move)
move = (13, 1)
game.opponent_play(move)
move = (13, 1)
game.opponent_play(move)
move = (2, 12)
game.opponent_play(move)
move = (2, 12)
game.opponent_play(move)
move = (2, 12)
game.opponent_play(move)
move = (2, 12)
game.opponent_play(move)
move = (2, 12)
game.opponent_play(move)
move = (3, 11)
game.opponent_play(move)
move = (3, 11)
game.opponent_play(move)
move = (3, 11)
game.opponent_play(move)
move = (3, 11)
game.opponent_play(move)
move = (3, 11)
game.opponent_play(move)
move = (4, 10)
game.opponent_play(move)
move = (4, 10)
game.opponent_play(move)
move = (4, 10)
game.opponent_play(move)
move = (4, 10)
game.opponent_play(move)
move = (4, 10)
game.opponent_play(move)
move = (5, 9)
game.opponent_play(move)
move = (5, 9)
game.opponent_play(move)
move = (5, 9)
game.opponent_play(move)
move = (5, 9)
game.opponent_play(move)
move = (5, 9)
game.opponent_play(move)


game.print_board()

print(game.possible_movements(1))
